<?php

namespace CoreBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TimeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TimeRepository extends EntityRepository
{
}
